/** @type {import('prettier').Options} */
export default {
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  quoteProps: 'consistent',
  arrowParens: 'always',
  plugins: ['prettier-plugin-tailwindcss'],
  tailwindAttributes: [
    'class',
    'className',
    'headerClassName',
    'contentContainerClassName',
    'columnWrapperClassName',
    'endFillColorClassName',
    'imageClassName',
    'tintColorClassName',
    'ios_backgroundColorClassName',
    'thumbColorClassName',
    'trackColorOnClassName',
    'trackColorOffClassName',
    'selectionColorClassName',
    'cursorColorClassName',
    'underlineColorAndroidClassName',
    'placeholderTextColorClassName',
    'selectionHandleColorClassName',
    'colorsClassName',
    'progressBackgroundColorClassName',
    'titleColorClassName',
    'underlayColorClassName',
    'colorClassName',
    'drawerBackgroundColorClassName',
    'statusBarBackgroundColorClassName',
    'backdropColorClassName',
    'backgroundColorClassName',
    'ListFooterComponentClassName',
    'ListHeaderComponentClassName',
    'cva\\(([^)]*)\\)',
    '["\'`]([^"\'`]*).*?["\'`]',
    'cn\\(([^)]*)\\)',
    '["\'`]([^"\'`]*).*?["\'`]',
  ],
  tailwindFunctions: ['useResolveClassNames', 'useCSSVariable'],
}
